### ISSUE TITLE
环境变量的展示问题

### ISSUE THREAD

**Issue by Greyh4t** [guonaihong/clop#69]
目前 --help 输出的结果中，环境变量是展示在命令行结尾和Args这两个地方的
展示在命令行结尾语义上有点奇怪，感觉是命令行的可选参数
展示在Args里与真正的args参数混淆了
如果把命令行单独拎出来，展示在 Environment Variables 块里，是不是更好呢，而且放到这个块里之后，容易理解，环境变量名对齐就很好看了，也不用尖括号包起来，容易复制，并且变量名出现过之后，在后面的用法说明处其实就没有必要再重复出现了，类似这样
```
Usage:
    ./testcode [Flags] <files> 

Flags:
    --number                 number all output lines [env: NUMBER=]
    --number-nonblank        number nonempty output lines, overrides [env: NUMBER_NON_BLANK=]
    --show-ends              display $ at end of each line [env: SHOW_ENDS=]
    -T,--show-tab            display TAB characters as ^I
    -s,--squeeze-blank       suppress repeated empty output lines
    -v,--show-nonprinting    use ^ and M- notation, except for LFD and TAB

Args:
    <files>

Environment Variables:
    NUMBER_NON_BLANK        number nonempty output lines, overrides
    SHOW_ENDS               display $ at end of each line
    NUMBER                  number all output lines
```

**Comment by guonaihong** [comment]
可以，我这两天加上。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [guonaihong/clop] 环境变量的展示问题 (Issue #69)




 
目前 --help 输出的结果中，环境变量是展示在命令行结尾和Args这两个地方的
 展示在命令行结尾语义上有点奇怪，感觉是命令行的可选参数
 展示在Args里与真正的args参数混淆了
 如果把命令行单独拎出来，展示在 Environment Variables 块里，是不是更好呢，而且放到这个块里之后，容易理解，环境变量名对齐就很好看了，也不用尖括号包起来，容易复制，并且变量名出现过之后，在后面的用法说明处其实就没有必要再重复出现了，类似这样
 Usage:     ./testcode [Flags] <files&gt;  Flags:     --number                 number all output lines [env: NUMBER=]     --number-nonblank        number nonempty output lines, overrides [env: NUMBER_NON_BLANK=]     --show-ends              display $ at end of each line [env: SHOW_ENDS=]     -T,--show-tab            display TAB characters as ^I     -s,--squeeze-blank       suppress repeated empty output lines     -v,--show-nonprinting    use ^ and M- notation, except for LFD and TAB Args:     <files&gt; Environment Variables:     NUMBER_NON_BLANK        number nonempty output lines, overrides     SHOW_ENDS               display $ at end of each line     NUMBER                  number all output lines  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Greyh4t** [comment]
感觉环境变量不加=号是不是更好，与单独列出来的项正好对应
```
Usage:
    ./testcode [Flags] <files> 

Flags:
    --number                 number all output lines [env: NUMBER]
    --number-nonblank        number nonempty output lines, overrides [env: NUMBER_NON_BLANK]
    --show-ends              display $ at end of each line [env: SHOW_ENDS]
    -T,--show-tab            display TAB characters as ^I
    -s,--squeeze-blank       suppress repeated empty output lines
    -v,--show-nonprinting    use ^ and M- notation, except for LFD and TAB

Args:
    <files>

Environment Variables:
    NUMBER_NON_BLANK        number nonempty output lines, overrides
    SHOW_ENDS               display $ at end of each line
    NUMBER                  number all output lines
```

**Comment by guonaihong** [comment]
> 感觉环境变量不加=号是不是更好，与单独列出来的项正好对应
> 
> ```
> Usage:
>     ./testcode [Flags] <files> 
> 
> Flags:
>     --number                 number all output lines [env: NUMBER]
>     --number-nonblank        number nonempty output lines, overrides [env: NUMBER_NON_BLANK]
>     --show-ends              display $ at end of each line [env: SHOW_ENDS]
>     -T,--show-tab            display TAB characters as ^I
>     -s,--squeeze-blank       suppress repeated empty output lines
>     -v,--show-nonprinting    use ^ and M- notation, except for LFD and TAB
> 
> Args:
>     <files>
> 
> Environment Variables:
>     NUMBER_NON_BLANK        number nonempty output lines, overrides
>     SHOW_ENDS               display $ at end of each line
>     NUMBER                  number all output lines
> ```

可以.

**Comment by guonaihong** [comment]
@Greyh4t 用下v0.1.4版本.

**Comment by Greyh4t** [comment]
> @Greyh4t 用下v0.1.4版本.

效率真高，赞一个。试用了一下发现个问题，Options块中，参数描述的内容和环境变量之间没有空格，但是Flags里是有的，Options里是不是漏了，类似这样

```
Usage:
    ./testcode [Flags] <files> 

Flags:
    --number                 number all output lines [env: NUMBER]
    --number-nonblank        number nonempty output lines, overrides [env: NUMBER_NON_BLANK]
    --show-ends              display $ at end of each line [env: SHOW_ENDS]
    -T,--show-tab            display TAB characters as ^I
    -s,--squeeze-blank       suppress repeated empty output lines
    -v,--show-nonprinting    use ^ and M- notation, except for LFD and TAB

Options:
    --email                  email[env: EMAIL]

Args:
    <files>

Environment Variables:
    NUMBER_NON_BLANK         number nonempty output lines, overrides
    SHOW_ENDS                display $ at end of each line
    NUMBER                   number all output lines
```

**Comment by guonaihong** [comment]
@Greyh4t 优秀, 是和空格有关系. 你可以提个pr优化下.
